version: "3.9"

services:
  postgres:
    image: "postgres:13.3"
    container_name: "java-postgres"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  name_generator:
    build: ./name-generator
    depends_on:
      - postgres
    container_name: "name-generator"
    ports:
      - "8080:8080"