server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_SERVER_URL:http://localhost:8484/auth}/realms/my_realm/protocol/openid-connect/certs

api:
  name-generation:
    url: ${NAMEGEN_URL:http://localhost:8080}/api/generate