server:
  port: 0

spring:
  application:
    name: pet-registration
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  security:
    oauth2:
      client:
        registration:
          external:
            client-id: "my_client"
            client-secret: "dOrAUhZmOr66rHl7YQ5fJExAcqA03F8h"
            authorization-grant-type: client_credentials
        provider:
          external:
            token-uri: ${KEYCLOAK_SERVER_URL:http://localhost:8484/auth}/realms/my_realm/protocol/openid-connect/token