server:
  port: 0

spring:
  application:
    name: name-generator
  liquibase:
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: kafka0:29090
  cloud:
    stream:
      bindings:
        producer-out-0:
          destination: user-events
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_SERVER_URL:http://localhost:8484/auth}/realms/my_realm/protocol/openid-connect/certs

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761}/eureka


app:
  keycloak:
    enabled: true
