server:
  tomcat:
    relaxed-query-chars: ['{','}','[',']']

spring:
  liquibase:
    enabled: true
  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://postgres:5432/postgres
    url: jdbc:h2:mem:postgres
    driverClassName: org.h2.Driver
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: kafka0:29090
  cloud:
    stream:
      bindings:
        producer-out-0:
          destination: user-events
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_SERVER_URL:http://localhost:8484/auth}/realms/my_realm/protocol/openid-connect/certs

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
