server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arshak-aivazian/petservice-config.git
          clone-on-start: true
          basedir: file://c:/tmp/git-c
          default-label: main
